spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 30000

alibaba:
  cloud:
    access-key: LTAI5tRH8nFmpzE9yq9H4GhT
    secret-key: RBOVF9iIWb7QXAEzmqFOPzdQlS6Ih7
    bucket: gulimall-1223912573
    oss:
      endpoint: oss-cn-guangzhou.aliyuncs.com

